---
kind: pipeline
type: docker
privileged: true
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Test
  image: fr3akyphantom/droid-builder:focal
  commands:
  - pwd && ls -lAog
  - sudo mkdir -p /opt/ffmpeg_build
  - sudo chmod 777 /opt/ffmpeg_build -R
  - sudo chown builder:builder /opt/ffmpeg_build -R
  - cd /opt/ffmpeg_build
  - curl -sL https://github.com/rokibhasansagar/ffmpeg-build-script/raw/update3/build-ffmpeg -O
  - chmod a+x build-ffmpeg
  - sudo apt-get update -qqy
  - sudo apt-get -qqy install build-essential curl ca-certificates libva-dev va-driver-all mercurial python3 python-is-python3
  - echo && date && echo
  - SKIPINSTALL=yes NUMJOBS=12 ./build-ffmpeg --build --enable-gpl-and-non-free --full-static
  - echo && date && echo
  - ls -lAog ./workspace/bin/
  - cd workspace/bin/
  - curl -s --upload-file ./ffmpeg https://transfer.sh && echo
  - curl -s --upload-file ./ffprobe https://transfer.sh && echo
  - curl -s --upload-file ./ffplay https://transfer.sh && echo
  - curl -s --upload-file ./x264 https://transfer.sh && echo
  - curl -s --upload-file ./x265 https://transfer.sh && echo
  - ./x265 -V
  - ./ffmpeg -help
  - df -hlT
  - wget -q "https://gdrive.phantomzone.workers.dev/0:/TorrentXbot/Miraculous.Tales.Of.Ladybug.&.Cat.Noir.(2015).Miraculous.World.Shanghai.The.Legend.of.Ladydragon.720p.TF1.ENGLISH.WEB-DL.2CH.H264%20-%20PGPirate.mkv" -O test.mkv
  - ./ffmpeg -hide_banner -i test.mkv -t 45 -map_metadata -1 -map 0:0 -c:v libx265 -vtag hvc1 -preset slower -tune animation -crf 23 -x265-params frame-threads=4:pmode=1 encoded.mkv
  - mediainfo ./encoded.mkv
  - curl -s --upload-file ./encoded.mkv https://transfer.sh && echo
