---
kind: pipeline
type: docker
privileged: true
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Test
  image: fr3akyphantom/droid-builder:focal
  commands:
  - sudo apt-get update -qqy && sudo apt-get install -qqy mediainfo libva-dev
  - wget -q "https://github.com/rokibhasansagar/FFmpeg-Builds/releases/download/autobuild-2021-12-24-03-27/ffmpeg-n4.4.1-2-gcc33e73618-linux64-nonfree-4.4.tar.xz"
  - tar -xJf ffmpeg*.tar.xz --strip-components 1
  - sudo mv bin/* /usr/local/bin/
  - mkdir -p ~/test && cd ~/test
  - wget -q "https://gdrivecdn4.phantomdroidy.workers.dev/0:/Another_MiraculouStreams/S01E01/SourceVideoChunks/Miraculous.Tales.of.Ladybug.and.Cat.Noir.S01E01.1080p.part_01.mkv" -O test.mkv
  - ffmpeg -hide_banner -stats_period 10 -y -i test.mkv -map_metadata -1 -map 0:0 -c:v libx265 -vtag hvc1 -vf scale=-2:480 -g 100 -keyint_min 25 -preset slower -tune animation -crf 25 -x265-params pools=12:frame-threads=2:pmode=1:ssim-rd=1:psy-rd=0.4:ssim=1:psnr=1 encoded.mkv
  - mediainfo ./encoded.mkv
  - curl -s --upload-file ./encoded.mkv https://transfer.sh && echo
