---
kind: pipeline
type: docker
privileged: true
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Test
  image: fr3akyphantom/droid-builder:focal
  commands:
  - sudo apt-get update -qqy && sudo apt-get install -qqy mediainfo libva-dev
  - cd "$(mktemp -d)"
  - export FTOOL_URL=$(curl -sL "https://api.github.com/repos/rokibhasansagar/FFmpeg-Builds/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("linux64-nonfree-4.4.tar.xz")) | .browser_download_url')
  - [[ -z ${FTOOL_URL} ]] && export FTOOL_URL=$(curl -sL "https://api.github.com/repos/rokibhasansagar/FFmpeg-Builds/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("linux64-nonfree-4.4.tar.xz")) | .browser_download_url')
  - wget -q ${FTOOL_URL} || curl -sL ${FTOOL_URL} -O
  - tar -xJf ff*.tar.xz --strip-components 1
  - sudo mv bin/* /usr/local/bin/
  - cd -
  - mkdir -p ~/test && cd ~/test
  - wget -q "https://gdrivecdn4.phantomdroidy.workers.dev/0:/Another_MiraculouStreams/S01E01/SourceVideoChunks/Miraculous.Tales.of.Ladybug.and.Cat.Noir.S01E01.1080p.part_01.mkv" -O test.mkv
  - ffmpeg -hide_banner -stats_period 10 -y -i test.mkv -map_metadata -1 -map 0:0 -c:v libx265 -vtag hvc1 -vf scale=-2:480 -g 100 -keyint_min 25 -preset slower -tune animation -crf 25 -x265-params pools=12:frame-threads=2:pmode=1:ssim-rd=1:psy-rd=0.4:ssim=1:psnr=1 encoded.mkv
  - mediainfo ./encoded.mkv
  - curl -s --upload-file ./encoded.mkv https://transfer.sh && echo
